/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImageModel } from '../../models/image-model';

export interface ApiImagePost$Plain$Params {
      body?: {
'Image'?: Blob;
}
}

export function apiImagePost$Plain(http: HttpClient, rootUrl: string, params?: ApiImagePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ImageModel>> {
  const rb = new RequestBuilder(rootUrl, apiImagePost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ImageModel>;
    })
  );
}

apiImagePost$Plain.PATH = '/api/Image';
