/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ParameterModel } from '../../models/parameter-model';

export interface ApiCityGet$Json$Params {
}

export function apiCityGet$Json(http: HttpClient, rootUrl: string, params?: ApiCityGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ParameterModel>>> {
  const rb = new RequestBuilder(rootUrl, apiCityGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ParameterModel>>;
    })
  );
}

apiCityGet$Json.PATH = '/api/City';
