/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ParameterModel } from '../models/parameter-model';
export interface DictionaryModel {
  cities: Array<ParameterModel>;
  eyesColors: Array<ParameterModel>;
  genders: Array<ParameterModel>;
  hairColors: Array<ParameterModel>;
  languages: Array<ParameterModel>;
  sexOrientations: Array<ParameterModel>;
  tags: Array<ParameterModel>;
  zodiacSigns: Array<ParameterModel>;
}
