/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImageModel } from '../models/image-model';
import { ParameterModel } from '../models/parameter-model';
export interface UserModel {
  birthdate: string;
  city: ParameterModel;
  description: string;
  eyesColor?: ParameterModel | null;
  firstname: string;
  gender: ParameterModel;
  hairColor?: ParameterModel | null;
  height?: number | null;
  id: number;
  languages: Array<ParameterModel>;
  maxPartnerHeight?: number | null;
  maxPartnerWeight?: number | null;
  maxPartnerYear?: number | null;
  minPartnerHeight?: number | null;
  minPartnerWeight?: number | null;
  minPartnerYear?: number | null;
  partnerCities: Array<ParameterModel>;
  partnerEyesColors: Array<ParameterModel>;
  partnerHairColors: Array<ParameterModel>;
  partnerZodiacSigns: Array<ParameterModel>;
  sexOrientation: ParameterModel;
  surname?: string | null;
  tags: Array<ParameterModel>;
  userImagesPathes: Array<ImageModel>;
  weight?: number | null;
}
