/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ParameterModel } from '../../models/parameter-model';

export interface ApiZodiacSignGet$Plain$Params {
}

export function apiZodiacSignGet$Plain(http: HttpClient, rootUrl: string, params?: ApiZodiacSignGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ParameterModel>>> {
  const rb = new RequestBuilder(rootUrl, apiZodiacSignGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ParameterModel>>;
    })
  );
}

apiZodiacSignGet$Plain.PATH = '/api/ZodiacSign';
