/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { DictionaryModel } from './models/dictionary-model';
export { ImageModel } from './models/image-model';
export { ParameterModel } from './models/parameter-model';
export { UserModel } from './models/user-model';
