/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { DictionaryService } from './services/dictionary.service';
export { ImageService } from './services/image.service';
export { TestService } from './services/test.service';
export { UserService } from './services/user.service';
