/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiDictionaryGet$Json } from '../fn/dictionary/api-dictionary-get-json';
import { ApiDictionaryGet$Json$Params } from '../fn/dictionary/api-dictionary-get-json';
import { apiDictionaryGet$Plain } from '../fn/dictionary/api-dictionary-get-plain';
import { ApiDictionaryGet$Plain$Params } from '../fn/dictionary/api-dictionary-get-plain';
import { DictionaryModel } from '../models/dictionary-model';

@Injectable({ providedIn: 'root' })
export class DictionaryService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiDictionaryGet()` */
  static readonly ApiDictionaryGetPath = '/Dictionary';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiDictionaryGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiDictionaryGet$Plain$Response(params?: ApiDictionaryGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DictionaryModel>> {
    return apiDictionaryGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiDictionaryGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiDictionaryGet$Plain(params?: ApiDictionaryGet$Plain$Params, context?: HttpContext): Observable<DictionaryModel> {
    return this.apiDictionaryGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<DictionaryModel>): DictionaryModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiDictionaryGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiDictionaryGet$Json$Response(params?: ApiDictionaryGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DictionaryModel>> {
    return apiDictionaryGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiDictionaryGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiDictionaryGet$Json(params?: ApiDictionaryGet$Json$Params, context?: HttpContext): Observable<DictionaryModel> {
    return this.apiDictionaryGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<DictionaryModel>): DictionaryModel => r.body)
    );
  }

}
