/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiTestTestGet$Json } from '../fn/test/api-test-test-get-json';
import { ApiTestTestGet$Json$Params } from '../fn/test/api-test-test-get-json';
import { apiTestTestGet$Plain } from '../fn/test/api-test-test-get-plain';
import { ApiTestTestGet$Plain$Params } from '../fn/test/api-test-test-get-plain';

@Injectable({ providedIn: 'root' })
export class TestService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiTestTestGet()` */
  static readonly ApiTestTestGetPath = '/api/Test/Test';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTestTestGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTestTestGet$Plain$Response(params?: ApiTestTestGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return apiTestTestGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTestTestGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTestTestGet$Plain(params?: ApiTestTestGet$Plain$Params, context?: HttpContext): Observable<string> {
    return this.apiTestTestGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTestTestGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTestTestGet$Json$Response(params?: ApiTestTestGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return apiTestTestGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTestTestGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTestTestGet$Json(params?: ApiTestTestGet$Json$Params, context?: HttpContext): Observable<string> {
    return this.apiTestTestGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
